-- AlterTable
ALTER TABLE "Promotion" ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "endDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "event" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;
